namespace SBC.Domain.Entities.Enums;

/// <summary>
/// Defines the type of account within a financial system.
/// </summary>
/// <remarks>
/// AccountType is used to categorize accounts based on their functional or financial purpose.
/// The possible values represent common accounting classifications:
/// - Asset: Represents resources owned by an entity.
/// - Liability: Represents obligations or debts owed by an entity.
/// - Equity: Represents the residual interest in the assets of an entity after deducting liabilities.
/// - Revenue: Represents income generated from operations or activities.
/// - Expense: Represents costs or expenditures incurred during operations.
/// </remarks>
public enum AccountType
{
    /// <summary>
    /// Represents resources owned by an entity within a financial system.
    /// </summary>
    /// <remarks>
    /// Accounts categorized as Asset typically include items such as cash, accounts receivable, inventory,
    /// property, and equipment. These resources are expected to provide economic benefits
    /// to the entity in the future.
    /// </remarks>
    Asset = 1, // Activo -- Balance general

    /// <summary>
    /// Represents obligations or debts owed by an entity within a financial system.
    /// </summary>
    /// <remarks>
    /// Accounts categorized as Liability typically include items such as loans, accounts payable,
    /// mortgages, and other financial obligations. These represent claims against the entity's
    /// resources that are expected to be settled through the transfer of assets or provision of services.
    /// </remarks>
    Liability = 2, // Pasivo -- Balance general

    /// <summary>
    /// Represents the residual interest in the assets of an entity after deducting liabilities.
    /// </summary>
    /// <remarks>
    /// Accounts categorized as Equity reflect ownership interest, retained earnings, or capital contributions.
    /// These accounts are typically used to measure the net worth of an entity within the accounting framework.
    /// </remarks>
    Equity = 3, // Patrimonio -- Balance general

    /// <summary>
    /// Represents income generated by an entity's operations or activities.
    /// </summary>
    /// <remarks>
    /// Accounts categorized as Revenue typically include earnings from sales, services, fees, interest,
    /// and other business operations. Revenue serves as a key financial metric indicating the
    /// financial performance of an entity over a specific period.
    /// </remarks>
    Revenue = 4, // Ingresos -- Estado de resultados

    /// <summary>
    /// Represents the outflow of resources or expenses incurred in the generation of revenue.
    /// </summary>
    /// <remarks>
    /// Accounts categorized as Cost typically include expenditures directly associated with
    /// producing goods or delivering services, such as materials, labor, and overhead.
    /// These are critical for determining profitability and assessing operational efficiency.
    /// </remarks>
    Cost = 5, // Costos -- estado de resultados

    /// <summary>
    /// Represents costs or expenditures incurred by an entity in the process of generating revenue.
    /// </summary>
    /// <remarks>
    /// Accounts categorized as Expense typically include operational costs such as salaries, rent,
    /// utilities, and depreciation. These accounts reflect the consumption of resources over a specific
    /// period and are essential for calculating net income or loss.
    /// </remarks>
    Expense = 6 // Gastos -- estado de resultados
}