// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SBC.Infrastructure.Database;

#nullable disable

namespace SBC.Infrastructure.Migrations
{
    [DbContext(typeof(SbcDbContext))]
    [Migration("20260309203012_SeedAccountCatalog")]
    partial class SeedAccountCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bc2bfc1-1e12-4b5f-a1ff-679b06b1996b"),
                            ConcurrencyStamp = "c735af80-37c2-434b-9c50-c8f3c5fd1be2",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("15babe3a-44b5-4045-81b2-d1e4ef87ce32"),
                            ConcurrencyStamp = "5150d7aa-213d-42a4-945e-5d60c96c6485",
                            Name = "Guest",
                            NormalizedName = "GUEST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "identity");
                });

            modelBuilder.Entity("SBC.Domain.Entities.Accounting.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("ParentAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentAccountId");

                    b.ToTable("Accounts", "accounting", t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_Code_NotEmpty", "LEN([Code]) > 0");

                            t.HasCheckConstraint("CK_Accounts_Name_NotEmpty", "LEN([Name]) > 0");

                            t.HasCheckConstraint("CK_Accounts_Type_Valid", "[Type] IN ('Asset', 'Liability', 'Equity', 'Revenue', 'Cost', 'Expense')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("3842cac4-b9a0-8223-0dcc-509a6f75849b"),
                            Code = "1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ACTIVO",
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("bb457d77-dfbc-d450-9c42-c70ad7acf5fe"),
                            Code = "1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ACTIVOS CIRCULANTES",
                            ParentAccountId = new Guid("3842cac4-b9a0-8223-0dcc-509a6f75849b"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("9ccd2c87-ce6d-ce18-6ea4-d5106540f089"),
                            Code = "1.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ACTIVOS DISPONIBLES",
                            ParentAccountId = new Guid("bb457d77-dfbc-d450-9c42-c70ad7acf5fe"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("13aa86e0-a17f-679f-d27b-39d0eca18610"),
                            Code = "1.1.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CAJA",
                            ParentAccountId = new Guid("9ccd2c87-ce6d-ce18-6ea4-d5106540f089"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("a52e29a6-cdb3-9e51-d93d-29cc07a883f0"),
                            Code = "1.1.1.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CAJA GENERAL",
                            ParentAccountId = new Guid("13aa86e0-a17f-679f-d27b-39d0eca18610"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("dbb04a13-bfcb-8e76-7837-d9bc42513c15"),
                            Code = "1.1.1.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CAJA CHICA",
                            ParentAccountId = new Guid("13aa86e0-a17f-679f-d27b-39d0eca18610"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("05086698-eecd-2a36-7483-27ad6032805b"),
                            Code = "1.1.1.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BANCOS",
                            ParentAccountId = new Guid("9ccd2c87-ce6d-ce18-6ea4-d5106540f089"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("c695234b-de5d-e1c5-d9e1-d15e752bfaa2"),
                            Code = "1.1.1.2.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "EMPRESA X CTA.CTE.#10012705215805",
                            ParentAccountId = new Guid("05086698-eecd-2a36-7483-27ad6032805b"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("ef332c52-a0dd-dcb8-6ce9-0c991beb9666"),
                            Code = "1.1.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ACTIVOS EXIGIBLES",
                            ParentAccountId = new Guid("bb457d77-dfbc-d450-9c42-c70ad7acf5fe"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("4b84144f-0594-c99f-a81d-2cb3ecb034e8"),
                            Code = "1.1.2.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CUENTAS POR COBRAR",
                            ParentAccountId = new Guid("ef332c52-a0dd-dcb8-6ce9-0c991beb9666"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("97434d56-efd7-d685-1bae-80c351fca817"),
                            Code = "1.1.2.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CUENTAS POR COBRAR CLIENTES",
                            ParentAccountId = new Guid("4b84144f-0594-c99f-a81d-2cb3ecb034e8"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("f05971ae-54e9-d7d9-037d-2d866d281f13"),
                            Code = "1.1.2.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CUENTAS POR COBRAR EMPLEADOS",
                            ParentAccountId = new Guid("4b84144f-0594-c99f-a81d-2cb3ecb034e8"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("c9f80cf2-4d00-b5dd-38fa-53ba0391b89d"),
                            Code = "1.1.2.1.003",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CUENTAS POR COBRAR OTROS",
                            ParentAccountId = new Guid("4b84144f-0594-c99f-a81d-2cb3ecb034e8"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("eb47bb3a-0fb4-8e75-50fd-8d1b0761b2bb"),
                            Code = "1.1.2.1.004",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ANTICIPO A JUSTIFICAR",
                            ParentAccountId = new Guid("4b84144f-0594-c99f-a81d-2cb3ecb034e8"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("18982fad-c120-6be2-9c95-b61832af190a"),
                            Code = "1.1.3",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ACTIVOS REALIZABLES",
                            ParentAccountId = new Guid("bb457d77-dfbc-d450-9c42-c70ad7acf5fe"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("faa6c09e-00ec-2d42-302e-294aba2005bb"),
                            Code = "1.1.3.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INVENTARIO DE MATERIALES",
                            ParentAccountId = new Guid("18982fad-c120-6be2-9c95-b61832af190a"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("07c24aa9-42ea-079c-6e46-1b4cbc06baf0"),
                            Code = "1.1.3.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INV. DE ACCESORIOS",
                            ParentAccountId = new Guid("faa6c09e-00ec-2d42-302e-294aba2005bb"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("aa28873d-a2ab-585f-1fee-beeae1a9147d"),
                            Code = "1.1.3.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INV. DE PAPERIA Y UTILES DE OFICINA",
                            ParentAccountId = new Guid("faa6c09e-00ec-2d42-302e-294aba2005bb"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("d5e7ff31-8436-74e3-b31b-a1d6ba97a786"),
                            Code = "1.1.3.1.003",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INV. DE MATERIALES Y LIMPIEZA",
                            ParentAccountId = new Guid("faa6c09e-00ec-2d42-302e-294aba2005bb"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("afec596b-3e4f-123e-194a-ae1cba1b3bb5"),
                            Code = "1.1.3.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INVENTARIO DE MERCADERIAS",
                            ParentAccountId = new Guid("18982fad-c120-6be2-9c95-b61832af190a"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("12be69f0-a634-3621-9fb7-55104857dbcc"),
                            Code = "1.1.3.2.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GRANOS BASICOS",
                            ParentAccountId = new Guid("afec596b-3e4f-123e-194a-ae1cba1b3bb5"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("98752b81-e8bb-cd81-8e5e-faa29fc2d684"),
                            Code = "1.1.4",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OTROS ACTIVOS CIRCULANTES",
                            ParentAccountId = new Guid("bb457d77-dfbc-d450-9c42-c70ad7acf5fe"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("196f42c8-9986-d647-79b6-6787d7b60150"),
                            Code = "1.1.4.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "IMPUESTOS ANTICIPADOS Y RETENIDOS",
                            ParentAccountId = new Guid("98752b81-e8bb-cd81-8e5e-faa29fc2d684"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("fe67dc69-32cd-aba3-c699-d6f33205b14f"),
                            Code = "1.1.4.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "IVA CREDITO TRIBUNAL",
                            ParentAccountId = new Guid("196f42c8-9986-d647-79b6-6787d7b60150"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("6493f394-6f81-5d94-13bf-9c15b10686d6"),
                            Code = "1.1.4.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ANTICIPO IMPUESTO A LA RENTA",
                            ParentAccountId = new Guid("196f42c8-9986-d647-79b6-6787d7b60150"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("bc3743f5-750f-9072-dce3-02ead55da913"),
                            Code = "1.1.4.1.003",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ANTICIPO RETENCION EN LA FUENTE",
                            ParentAccountId = new Guid("196f42c8-9986-d647-79b6-6787d7b60150"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("72547656-0468-4901-9c79-732468ba4340"),
                            Code = "1.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ACTIVOS FIJOS",
                            ParentAccountId = new Guid("3842cac4-b9a0-8223-0dcc-509a6f75849b"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("c666b7ac-7f06-6104-05f8-b1263b9e5172"),
                            Code = "1.2.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ACTIVOS TANGIBLES",
                            ParentAccountId = new Guid("72547656-0468-4901-9c79-732468ba4340"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("a1cadea3-6b99-6d1c-d169-7d5f2556f7be"),
                            Code = "1.2.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ACTIVOS DEPRECIABLES",
                            ParentAccountId = new Guid("c666b7ac-7f06-6104-05f8-b1263b9e5172"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("4858281d-8ec6-9401-b54e-35eaf2ea5a35"),
                            Code = "1.2.1.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INMUEBLES",
                            ParentAccountId = new Guid("a1cadea3-6b99-6d1c-d169-7d5f2556f7be"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("473eb7e9-df3d-e2af-7736-c83873def473"),
                            Code = "1.2.1.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INSTALACIONES",
                            ParentAccountId = new Guid("a1cadea3-6b99-6d1c-d169-7d5f2556f7be"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("d9955cc3-1288-55a9-f190-cd4067bb58b8"),
                            Code = "1.2.1.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ACTIVOS NO DEPRECIABLES",
                            ParentAccountId = new Guid("c666b7ac-7f06-6104-05f8-b1263b9e5172"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("b517f440-0d2b-4b7f-177b-881fb204523f"),
                            Code = "1.2.1.2.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TERRENO # 1",
                            ParentAccountId = new Guid("d9955cc3-1288-55a9-f190-cd4067bb58b8"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("c5ce6e69-6ea8-e419-d4df-56006eccda0b"),
                            Code = "1.2.1.3",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DEPRECIACION ACUMULDA",
                            ParentAccountId = new Guid("c666b7ac-7f06-6104-05f8-b1263b9e5172"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("d5e1e9e8-58e0-1b00-e6f0-b41429bc4458"),
                            Code = "1.2.1.3.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INMUEBLES DEP",
                            ParentAccountId = new Guid("c5ce6e69-6ea8-e419-d4df-56006eccda0b"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("a0954ed0-2da7-bac6-3890-9d9da858a7f2"),
                            Code = "1.2.1.3.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INSTALACIONES DEP",
                            ParentAccountId = new Guid("c5ce6e69-6ea8-e419-d4df-56006eccda0b"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("ae1d70bf-ff9a-b25b-2b8f-000dc9bf6199"),
                            Code = "1.2.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ACTIVOS INTANGIBLES",
                            ParentAccountId = new Guid("72547656-0468-4901-9c79-732468ba4340"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("8df70780-75bf-6674-f1f3-3a05292c3aa1"),
                            Code = "1.2.2.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MARCAS",
                            ParentAccountId = new Guid("ae1d70bf-ff9a-b25b-2b8f-000dc9bf6199"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("2ec895fd-fe31-8e1e-77b5-63482ba3fbf2"),
                            Code = "1.2.2.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SERVICIO DE EMPRESA",
                            ParentAccountId = new Guid("8df70780-75bf-6674-f1f3-3a05292c3aa1"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("b250719e-2cdc-36fd-ff9d-84827cd584e5"),
                            Code = "1.2.2.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MARCA DE PRODUCTO",
                            ParentAccountId = new Guid("8df70780-75bf-6674-f1f3-3a05292c3aa1"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("774856af-d174-b7e3-ce13-083119d763eb"),
                            Code = "1.2.2.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SOFTWARE",
                            ParentAccountId = new Guid("ae1d70bf-ff9a-b25b-2b8f-000dc9bf6199"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("27d353af-8e1f-7e03-3ab5-5a3442255f3c"),
                            Code = "1.2.2.2.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SOFTWARE CONTABLE",
                            ParentAccountId = new Guid("774856af-d174-b7e3-ce13-083119d763eb"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("f1c90e0b-28cc-c1b3-9dc6-c36dcd5af7cc"),
                            Code = "1.3",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OTROS ACTIVOS",
                            ParentAccountId = new Guid("3842cac4-b9a0-8223-0dcc-509a6f75849b"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("7ab5ac54-70fb-0f11-b7f8-e1de35e176b4"),
                            Code = "1.3.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ACTIVOS DIFERIDOS",
                            ParentAccountId = new Guid("f1c90e0b-28cc-c1b3-9dc6-c36dcd5af7cc"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("e87d3e46-ee55-c893-54a3-80b4969fd8b1"),
                            Code = "1.3.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GASTOS DE CONSTITUCION.",
                            ParentAccountId = new Guid("7ab5ac54-70fb-0f11-b7f8-e1de35e176b4"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("62fac3b9-f703-2e9d-d792-e8e218706f9d"),
                            Code = "1.3.1.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GASTOS DE CONSTITUCION",
                            ParentAccountId = new Guid("e87d3e46-ee55-c893-54a3-80b4969fd8b1"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("525df4d7-7aee-31f1-910f-7aa261128d7a"),
                            Code = "1.3.1.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GASTOS DE CONSTRUCCION.",
                            ParentAccountId = new Guid("7ab5ac54-70fb-0f11-b7f8-e1de35e176b4"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("38e6df38-cf8a-3ca8-3486-d41f22b08165"),
                            Code = "1.3.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OTROS ACTIVOS VARIOS",
                            ParentAccountId = new Guid("f1c90e0b-28cc-c1b3-9dc6-c36dcd5af7cc"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("3c1ca1bb-d9c1-61f8-3645-76bc485c05d1"),
                            Code = "1.3.2.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DEPOSITOD ENTREGADO EN GARANTIA",
                            ParentAccountId = new Guid("38e6df38-cf8a-3ca8-3486-d41f22b08165"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("91799361-9815-c5f2-18ca-7f3310389b5d"),
                            Code = "1.3.2.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INMUEBLES ENTREGADOS EN GARANTIA",
                            ParentAccountId = new Guid("3c1ca1bb-d9c1-61f8-3645-76bc485c05d1"),
                            Type = "Asset"
                        },
                        new
                        {
                            Id = new Guid("8d721ec8-4c9d-632f-6f06-7f89cc14862c"),
                            Code = "2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PASIVO",
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("757d2008-8a2d-6356-68d1-fd97b6142fa3"),
                            Code = "2.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PASIVOS A CORTO PLAZO",
                            ParentAccountId = new Guid("8d721ec8-4c9d-632f-6f06-7f89cc14862c"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("9031b59d-ad2d-bdda-db83-b22e9629f0ad"),
                            Code = "2.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CUENTAS POR PAGAR",
                            ParentAccountId = new Guid("757d2008-8a2d-6356-68d1-fd97b6142fa3"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("bfc8a6f5-e6d6-8bd1-4978-a5134c3ddc1e"),
                            Code = "2.1.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PROVEEDORES NACIONALES",
                            ParentAccountId = new Guid("9031b59d-ad2d-bdda-db83-b22e9629f0ad"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("d4767614-346d-fdd3-419c-e90872e2d2d2"),
                            Code = "2.1.1.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INDUSTRIALES CXP",
                            ParentAccountId = new Guid("bfc8a6f5-e6d6-8bd1-4978-a5134c3ddc1e"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("b36e7827-b3be-be30-3470-f4630df519d4"),
                            Code = "2.1.1.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PROVEEDORES LOCALES",
                            ParentAccountId = new Guid("9031b59d-ad2d-bdda-db83-b22e9629f0ad"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("c3eb59ee-e0b2-b98f-a474-e2075e164b8b"),
                            Code = "2.1.1.2.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PROVEEDOR X CXP",
                            ParentAccountId = new Guid("b36e7827-b3be-be30-3470-f4630df519d4"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("e70c4cd0-6059-c7c7-6a59-ea09e4101e63"),
                            Code = "2.1.1.3",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SERVICIOS POR PAGAR",
                            ParentAccountId = new Guid("9031b59d-ad2d-bdda-db83-b22e9629f0ad"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("f1bcd7c9-f9b5-ffc9-d12e-99f24c76cd16"),
                            Code = "2.1.1.3.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SERV. ENERGIA CXP",
                            ParentAccountId = new Guid("e70c4cd0-6059-c7c7-6a59-ea09e4101e63"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("b4f1ac33-f8b3-6db6-0031-1bab741ffda8"),
                            Code = "2.1.1.3.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TELEFONO E INTERNET CXP",
                            ParentAccountId = new Guid("e70c4cd0-6059-c7c7-6a59-ea09e4101e63"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("73ce7494-6d10-2853-c84e-dc9a7f9b2637"),
                            Code = "2.1.1.4",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OTRAS CUENTAS POR PAGAR",
                            ParentAccountId = new Guid("9031b59d-ad2d-bdda-db83-b22e9629f0ad"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("5a1249d2-0207-cca7-6340-3d8af5ed4dbf"),
                            Code = "2.1.1.4.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CUENTAS VARIAS POR PAGAR",
                            ParentAccountId = new Guid("73ce7494-6d10-2853-c84e-dc9a7f9b2637"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("0d876295-827e-d045-3c2a-c6055dff735f"),
                            Code = "2.1.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NOMINA POR PAGAR",
                            ParentAccountId = new Guid("757d2008-8a2d-6356-68d1-fd97b6142fa3"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("79c149f7-c0f0-bee9-516b-3aa825de2661"),
                            Code = "2.1.2.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "REMUNERACIONES POR PAGAR",
                            ParentAccountId = new Guid("0d876295-827e-d045-3c2a-c6055dff735f"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("8b2fd487-3dd7-0693-94a3-c8bc701278f3"),
                            Code = "2.1.2.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SUELDOS POR PAGAR",
                            ParentAccountId = new Guid("79c149f7-c0f0-bee9-516b-3aa825de2661"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("7d4a6143-5a4c-d1f9-ea57-9bbd17fbd00a"),
                            Code = "2.1.2.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DESCUENTOS POR ATRASOS",
                            ParentAccountId = new Guid("79c149f7-c0f0-bee9-516b-3aa825de2661"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("85326ad4-3b12-143b-a3f1-0487fd374020"),
                            Code = "2.1.2.1.003",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LIQUIDACIONES POR PAGAR",
                            ParentAccountId = new Guid("79c149f7-c0f0-bee9-516b-3aa825de2661"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("f0b4d215-484b-098d-7836-94890eb57cc4"),
                            Code = "2.1.2.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INSS E INATEC POR PAGAR",
                            ParentAccountId = new Guid("0d876295-827e-d045-3c2a-c6055dff735f"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("b0dd41f4-b175-c200-9b15-e5e9431f366b"),
                            Code = "2.1.2.2.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "APORTES PERSONAL Y PATRONAL CXP",
                            ParentAccountId = new Guid("f0b4d215-484b-098d-7836-94890eb57cc4"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("38efa72e-98a8-40bb-2b48-d7ad00e130d6"),
                            Code = "2.1.2.2.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INATEC POR PAGAR",
                            ParentAccountId = new Guid("f0b4d215-484b-098d-7836-94890eb57cc4"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("1da01327-c44b-cea8-26b3-fc7a88d44272"),
                            Code = "2.1.2.3",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PROVICIONES POR PAGAR",
                            ParentAccountId = new Guid("0d876295-827e-d045-3c2a-c6055dff735f"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("257f3d2e-f9e1-61e1-a4ee-ca228abdfee5"),
                            Code = "2.1.2.3.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DECIMO TERCER MES POR PAGAR",
                            ParentAccountId = new Guid("1da01327-c44b-cea8-26b3-fc7a88d44272"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("5fbdec57-dbf0-f6f0-8017-c174e31346d9"),
                            Code = "2.1.2.3.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "VACACIONES POR PAGAR",
                            ParentAccountId = new Guid("1da01327-c44b-cea8-26b3-fc7a88d44272"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("f780c1a7-84a9-f2a7-df1e-4a9c9b495a2d"),
                            Code = "2.1.2.3.003",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INDEMNIZACIONES POR PAGAR",
                            ParentAccountId = new Guid("1da01327-c44b-cea8-26b3-fc7a88d44272"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("d6971f6c-ec7f-253e-5c0c-b2279cc943de"),
                            Code = "2.1.3",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OBLIGACIONES FISCALES POR PAGAR",
                            ParentAccountId = new Guid("757d2008-8a2d-6356-68d1-fd97b6142fa3"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("a6daff80-8852-f23c-41b7-1e8accaf220e"),
                            Code = "2.1.3.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "IMPUESTOS POR PAGAR",
                            ParentAccountId = new Guid("d6971f6c-ec7f-253e-5c0c-b2279cc943de"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("0363d213-c9ce-d7ad-775a-8519b0f98e0c"),
                            Code = "2.1.3.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "IMPUESTO A LA RENTA POR PAGAR",
                            ParentAccountId = new Guid("a6daff80-8852-f23c-41b7-1e8accaf220e"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("a37e6afd-53e8-8256-2bcc-0f1a1c20dd1d"),
                            Code = "2.1.3.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "IVA POR PAGAR (15%)",
                            ParentAccountId = new Guid("a6daff80-8852-f23c-41b7-1e8accaf220e"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("266e4093-ff3e-dce8-5c15-018242515e34"),
                            Code = "2.1.3.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RETENCIONES FUENTE POR PAGAR",
                            ParentAccountId = new Guid("d6971f6c-ec7f-253e-5c0c-b2279cc943de"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("a7083d88-2f13-eda9-9346-bdb40410d938"),
                            Code = "2.1.3.2.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2% RET. FTE DE COMPRAS",
                            ParentAccountId = new Guid("266e4093-ff3e-dce8-5c15-018242515e34"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("de9277ca-b7e4-072f-6622-717675de5ce9"),
                            Code = "2.1.3.2.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "5% RET.FTE. SERVICIO",
                            ParentAccountId = new Guid("266e4093-ff3e-dce8-5c15-018242515e34"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("879ac69a-8156-7b3a-8564-b3bb360b10b3"),
                            Code = "2.1.3.2.003",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2% RET.FTE. SERVICIOS",
                            ParentAccountId = new Guid("266e4093-ff3e-dce8-5c15-018242515e34"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("44f7696f-3e31-0780-52b9-c0dc12ea8560"),
                            Code = "2.1.3.2.004",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "10% RET.FTE.HONORARIOS PROFESIONALES",
                            ParentAccountId = new Guid("266e4093-ff3e-dce8-5c15-018242515e34"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("9b056158-b76d-ba52-9c81-4c3accf7e261"),
                            Code = "2.1.3.3",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RETENCIONES IVA POR PAGAR",
                            ParentAccountId = new Guid("d6971f6c-ec7f-253e-5c0c-b2279cc943de"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("8409a2b7-6118-8543-2b31-2423775ac901"),
                            Code = "2.1.3.3.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "15% RET. IVA VENTAS",
                            ParentAccountId = new Guid("9b056158-b76d-ba52-9c81-4c3accf7e261"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("ade886b2-349b-bbd0-0241-ed78624440f7"),
                            Code = "2.1.3.4",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OTROS IMPUESTOS POR PAGAR",
                            ParentAccountId = new Guid("d6971f6c-ec7f-253e-5c0c-b2279cc943de"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("6a00dc2b-cbeb-d874-5c4b-e559ddb582e3"),
                            Code = "2.1.3.5",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RETENCIONES SOBRE SALARIO",
                            ParentAccountId = new Guid("d6971f6c-ec7f-253e-5c0c-b2279cc943de"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("46cc841a-eb91-91d8-af99-065de15e703d"),
                            Code = "2.1.3.5.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RETENCIONES SOBRE SALARIO DGI XP",
                            ParentAccountId = new Guid("6a00dc2b-cbeb-d874-5c4b-e559ddb582e3"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("79d51817-1186-6a0b-f2dd-96b59d3db416"),
                            Code = "2.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PASIVOS A LARGO PLAZO",
                            ParentAccountId = new Guid("8d721ec8-4c9d-632f-6f06-7f89cc14862c"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("b27a832c-cac7-dcdb-35b5-bd7115e9eff1"),
                            Code = "2.2.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PRESTAMOS A LARGO PLAZO",
                            ParentAccountId = new Guid("79d51817-1186-6a0b-f2dd-96b59d3db416"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("23ace421-f903-1c88-b4c1-acd2adc2ad6d"),
                            Code = "2.2.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PRESTMOS SOCIOS LARGO PLAZO",
                            ParentAccountId = new Guid("b27a832c-cac7-dcdb-35b5-bd7115e9eff1"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("07da8880-1255-0ae2-f774-1a081e52b977"),
                            Code = "2.2.1.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "R.G. PMO LARGO PLAZO",
                            ParentAccountId = new Guid("23ace421-f903-1c88-b4c1-acd2adc2ad6d"),
                            Type = "Liability"
                        },
                        new
                        {
                            Id = new Guid("7ec8cbec-5c4b-fee2-2830-8fd9f2a7baf3"),
                            Code = "3",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PATRIMONIO",
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("958a065b-2c44-557d-05b4-166a77357ea5"),
                            Code = "3.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PATRIMONIO NEGOCIO X",
                            ParentAccountId = new Guid("7ec8cbec-5c4b-fee2-2830-8fd9f2a7baf3"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("755be1d9-1199-386e-f870-d0dc600c08a4"),
                            Code = "3.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CAPITAL SOCIAL",
                            ParentAccountId = new Guid("958a065b-2c44-557d-05b4-166a77357ea5"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("3626acf5-7033-ca29-b4b4-12086549cedb"),
                            Code = "3.1.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CAPITAL PAGADO",
                            ParentAccountId = new Guid("755be1d9-1199-386e-f870-d0dc600c08a4"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("d0dd85ee-228b-9388-2484-985e2589052a"),
                            Code = "3.1.1.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CAPITAL NEGOCIO X",
                            ParentAccountId = new Guid("3626acf5-7033-ca29-b4b4-12086549cedb"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("50004e1f-f96f-5ffb-e179-f2ba1c60ff61"),
                            Code = "3.1.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RESERVAS",
                            ParentAccountId = new Guid("958a065b-2c44-557d-05b4-166a77357ea5"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("3673955b-2b17-e07b-0ee4-a120d4395d53"),
                            Code = "3.1.2.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RESERVAS PATRIMONIALES",
                            ParentAccountId = new Guid("50004e1f-f96f-5ffb-e179-f2ba1c60ff61"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("c92eaec2-b569-ea16-edb5-bb72dd6e5ac2"),
                            Code = "3.1.2.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RESERVA FACULTATIVA",
                            ParentAccountId = new Guid("3673955b-2b17-e07b-0ee4-a120d4395d53"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("a31ab429-8b95-89a0-6be3-7863ea265ace"),
                            Code = "3.1.2.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RESERVA DE CAPITAL",
                            ParentAccountId = new Guid("3673955b-2b17-e07b-0ee4-a120d4395d53"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("1a018f25-53e3-fa4d-8a66-eaca84eaf11b"),
                            Code = "3.1.2.1.003",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RESERVA LEGAL",
                            ParentAccountId = new Guid("3673955b-2b17-e07b-0ee4-a120d4395d53"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("569817b1-37b0-b82c-7779-75cb658548ac"),
                            Code = "3.1.3",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RESULTADOS",
                            ParentAccountId = new Guid("958a065b-2c44-557d-05b4-166a77357ea5"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("17d217b3-e15f-c6b0-9aac-10ce7974ae03"),
                            Code = "3.1.3.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RESULTADOS ANTERIORES",
                            ParentAccountId = new Guid("569817b1-37b0-b82c-7779-75cb658548ac"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("b8cc9014-90f3-97b3-612c-049111fccf0f"),
                            Code = "3.1.3.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "UTILIDADES ANTERIORES",
                            ParentAccountId = new Guid("17d217b3-e15f-c6b0-9aac-10ce7974ae03"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("e149409e-ff82-ec4e-3341-5197c827d6bd"),
                            Code = "3.1.3.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PERDIDAS ANTERIORES",
                            ParentAccountId = new Guid("17d217b3-e15f-c6b0-9aac-10ce7974ae03"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("954d67be-fbd3-a55b-00b2-34d0a39b26c4"),
                            Code = "3.1.3.1.003",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AMORTIZACION PERDIDAS ANTERIORES",
                            ParentAccountId = new Guid("17d217b3-e15f-c6b0-9aac-10ce7974ae03"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("767f1fc0-1ba4-7a2d-576a-352f788142ab"),
                            Code = "3.1.3.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RESULTADOS DEL EJERCICIO",
                            ParentAccountId = new Guid("569817b1-37b0-b82c-7779-75cb658548ac"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("a7716697-fbbf-6e26-bcbc-41a6f4eb3b84"),
                            Code = "3.1.3.2.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "UTILIDADES DE EJERCICIO",
                            ParentAccountId = new Guid("767f1fc0-1ba4-7a2d-576a-352f788142ab"),
                            Type = "Equity"
                        },
                        new
                        {
                            Id = new Guid("79f67fa8-f3a2-1de7-9181-a67b7542122c"),
                            Code = "4",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INGRESOS",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = new Guid("4a075a89-215b-2263-121b-5f76bc831927"),
                            Code = "4.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "INGRESOS OPERACIONALES",
                            ParentAccountId = new Guid("79f67fa8-f3a2-1de7-9181-a67b7542122c"),
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = new Guid("95a97e73-213b-ffc4-abc3-49e9b20f3b4b"),
                            Code = "4.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "VENTAS NETAS",
                            ParentAccountId = new Guid("4a075a89-215b-2263-121b-5f76bc831927"),
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = new Guid("7eaedbd3-ce30-a908-e7c8-7de13cbbb3a7"),
                            Code = "4.1.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "VENTAS DE GRANOS BASICOS",
                            ParentAccountId = new Guid("95a97e73-213b-ffc4-abc3-49e9b20f3b4b"),
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = new Guid("27be1f94-a9a8-fa73-c98e-33b275b550f6"),
                            Code = "4.1.1.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "VENTAS GENERALES",
                            ParentAccountId = new Guid("7eaedbd3-ce30-a908-e7c8-7de13cbbb3a7"),
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = new Guid("7f3bdae4-cebb-4523-d777-2b0674a318d5"),
                            Code = "5",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "COSTOS",
                            Type = "Cost"
                        },
                        new
                        {
                            Id = new Guid("4f19ff43-0f41-933e-a868-0bef5ba51e50"),
                            Code = "5.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "COSTOS OPERACIONALES",
                            ParentAccountId = new Guid("7f3bdae4-cebb-4523-d777-2b0674a318d5"),
                            Type = "Cost"
                        },
                        new
                        {
                            Id = new Guid("4bc20f2c-303d-3138-7dc5-1c05339856d0"),
                            Code = "5.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "COSTO DE VENTA",
                            ParentAccountId = new Guid("4f19ff43-0f41-933e-a868-0bef5ba51e50"),
                            Type = "Cost"
                        },
                        new
                        {
                            Id = new Guid("7f9435aa-977b-1298-11a6-9de1b591ab17"),
                            Code = "5.1.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "COSTOS DE VENTAS GRANOS BASICO",
                            ParentAccountId = new Guid("4bc20f2c-303d-3138-7dc5-1c05339856d0"),
                            Type = "Cost"
                        },
                        new
                        {
                            Id = new Guid("ba20cb9d-8cfe-6b83-1cc0-a72fb3e48c23"),
                            Code = "5.1.1.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "COSTO GRANOS BASICO",
                            ParentAccountId = new Guid("7f9435aa-977b-1298-11a6-9de1b591ab17"),
                            Type = "Cost"
                        },
                        new
                        {
                            Id = new Guid("1c097916-885a-af0f-6fb5-e6087eb1b2dc"),
                            Code = "6",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GASTOS",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("c382ebd6-ca24-f3b2-6e34-5863fad95090"),
                            Code = "6.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GASTOS OPERACIONALES",
                            ParentAccountId = new Guid("1c097916-885a-af0f-6fb5-e6087eb1b2dc"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("db2b5881-4a25-e494-4644-24087c6479a8"),
                            Code = "6.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GASTOS DE ADMINISTRACION",
                            ParentAccountId = new Guid("c382ebd6-ca24-f3b2-6e34-5863fad95090"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("f5a4aba4-d301-f98e-d4d3-01f1d08d4969"),
                            Code = "6.1.1.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SUELDOS Y SIMILARES ADMON",
                            ParentAccountId = new Guid("db2b5881-4a25-e494-4644-24087c6479a8"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("40f69734-81c9-7422-f498-60850cb237e6"),
                            Code = "6.1.1.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SUELDOS Y SALARIOS ADMON",
                            ParentAccountId = new Guid("f5a4aba4-d301-f98e-d4d3-01f1d08d4969"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("e98ee395-a07e-8a8a-bf51-1e36a5ac6aab"),
                            Code = "6.1.1.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "COMPONENTE SALARIAL ADM",
                            ParentAccountId = new Guid("f5a4aba4-d301-f98e-d4d3-01f1d08d4969"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("a8c0cb02-b212-7879-117e-da3922c99fcb"),
                            Code = "6.1.1.1.003",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HORA EXTRA ADM",
                            ParentAccountId = new Guid("f5a4aba4-d301-f98e-d4d3-01f1d08d4969"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("cda3be13-90e5-7c99-1094-f9bba14d719a"),
                            Code = "6.1.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GASTOS DE VENTAS",
                            ParentAccountId = new Guid("c382ebd6-ca24-f3b2-6e34-5863fad95090"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("fe1cc2bd-fc34-b430-032c-77dce53c3db7"),
                            Code = "6.1.2.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SUELDOS Y SIMILARES",
                            ParentAccountId = new Guid("cda3be13-90e5-7c99-1094-f9bba14d719a"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("313d34ad-48e4-59a5-7aec-8fabcf67c423"),
                            Code = "6.1.2.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SUELDOS Y SALARIOS DE VENTAS",
                            ParentAccountId = new Guid("fe1cc2bd-fc34-b430-032c-77dce53c3db7"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("4c431c65-3643-9525-c750-c51871bcf52d"),
                            Code = "6.1.2.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "COMPROBANTE SALARIAL DE VTA",
                            ParentAccountId = new Guid("fe1cc2bd-fc34-b430-032c-77dce53c3db7"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("6ebcf058-ade8-58e6-5253-ea8439434788"),
                            Code = "6.1.2.1.003",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HORAS EXTRAS VTAS",
                            ParentAccountId = new Guid("fe1cc2bd-fc34-b430-032c-77dce53c3db7"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("34baba1e-f365-0691-375b-e623a0ebab45"),
                            Code = "6.1.3",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GASTOS FINANCIEROS",
                            ParentAccountId = new Guid("c382ebd6-ca24-f3b2-6e34-5863fad95090"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("211015fc-50c4-e649-5733-166abc4b98aa"),
                            Code = "6.1.3.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GASTOS BANCARIOS",
                            ParentAccountId = new Guid("34baba1e-f365-0691-375b-e623a0ebab45"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("b0ab5b5b-990c-3464-6812-cd761197a647"),
                            Code = "6.1.3.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GTOS BANC.X CHEQUERA",
                            ParentAccountId = new Guid("211015fc-50c4-e649-5733-166abc4b98aa"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("d2d33fc7-e48b-40d0-9b38-0b55f70f3b4a"),
                            Code = "6.1.3.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GAST.X SERV.BANC.",
                            ParentAccountId = new Guid("211015fc-50c4-e649-5733-166abc4b98aa"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("5643c345-4bf4-7d01-36e9-ca732b95d6ab"),
                            Code = "6.1.3.1.003",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GAST. X DEVALUACION DE LA MONEDA FIN.",
                            ParentAccountId = new Guid("211015fc-50c4-e649-5733-166abc4b98aa"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("4ab5517f-c03f-255c-effb-04f483552de7"),
                            Code = "6.1.4",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GASTOS GENERALES",
                            ParentAccountId = new Guid("c382ebd6-ca24-f3b2-6e34-5863fad95090"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("15ef207e-9661-34db-373f-49975ba2dee4"),
                            Code = "6.1.4.1",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MANTENIMIENTO DE MUEBLES Y ENSERES GEN",
                            ParentAccountId = new Guid("4ab5517f-c03f-255c-effb-04f483552de7"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("a5f5bfc1-dea1-2df2-c202-60b26aac0a37"),
                            Code = "6.1.4.1.001",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MANT. DE MUEBLES GEN",
                            ParentAccountId = new Guid("15ef207e-9661-34db-373f-49975ba2dee4"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("ee6c0412-accd-8edf-21ca-73ab74c14dc7"),
                            Code = "6.1.4.1.002",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MANT. DE ENSERES GEN",
                            ParentAccountId = new Guid("15ef207e-9661-34db-373f-49975ba2dee4"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("aaec7a79-7dd5-229e-d7ad-51ffb466c25d"),
                            Code = "6.1.4.2",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CONS. DE ENEGIA ELECTRICA GEN",
                            ParentAccountId = new Guid("4ab5517f-c03f-255c-effb-04f483552de7"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("21e7b256-5e0f-2a49-9282-1735e7c895b6"),
                            Code = "6.1.4.2.01",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CONS.ENEGIA ENEL GEN",
                            ParentAccountId = new Guid("aaec7a79-7dd5-229e-d7ad-51ffb466c25d"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("656b93a7-5040-e593-bc2a-017ff28354f9"),
                            Code = "6.1.4.3",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MOVILIZACIONE LOCALE GEN",
                            ParentAccountId = new Guid("4ab5517f-c03f-255c-effb-04f483552de7"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("43b2c282-b427-8cbc-a086-6048dd1fd5ed"),
                            Code = "6.1.4.3.003",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "VIATICOS GEN",
                            ParentAccountId = new Guid("656b93a7-5040-e593-bc2a-017ff28354f9"),
                            Type = "Expense"
                        },
                        new
                        {
                            Id = new Guid("ce8cda09-a336-fba3-08bf-bdaf87d7e881"),
                            Code = "6.1.4.3.004",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PASAJES AEREOS GEN.",
                            ParentAccountId = new Guid("656b93a7-5040-e593-bc2a-017ff28354f9"),
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("SBC.Domain.Entities.Accounting.AccountingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ClosingJournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<short>("Month")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ClosingJournalEntryId");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("AccountingPeriods", "accounting", t =>
                        {
                            t.HasCheckConstraint("CK_AccountingPeriods_Month_Valid", "[Month] >= 1 AND [Month] <= 12");

                            t.HasCheckConstraint("CK_AccountingPeriods_Year_Valid", "[Year] >= 1900");
                        });
                });

            modelBuilder.Entity("SBC.Domain.Entities.Accounting.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<short>("Day")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsPosted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<short>("Month")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("JournalEntries", "accounting", t =>
                        {
                            t.HasCheckConstraint("CK_JournalEntries_Code_NotEmpty", "LEN([Code]) > 0");

                            t.HasCheckConstraint("CK_JournalEntries_Day_Valid", "[Day] >= 1 AND [Day] <= 31");

                            t.HasCheckConstraint("CK_JournalEntries_Description_NotEmpty", "[Description] IS NULL OR LEN([Description]) > 0");

                            t.HasCheckConstraint("CK_JournalEntries_Month_Valid", "[Month] >= 1 AND [Month] <= 12");

                            t.HasCheckConstraint("CK_JournalEntries_Year_Valid", "[Year] >= 1900");
                        });
                });

            modelBuilder.Entity("SBC.Domain.Entities.Accounting.JournalEntryLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Credit")
                        .HasColumnType("money");

                    b.Property<decimal>("Debit")
                        .HasColumnType("money");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("JournalEntryLines", "accounting", t =>
                        {
                            t.HasCheckConstraint("CK_JournalEntryLines_Credit_NoNegative", "[Credit] >= 0");

                            t.HasCheckConstraint("CK_JournalEntryLines_Debit_NoNegative", "[Debit] >= 0");

                            t.HasCheckConstraint("CK_JournalEntryLines_HasValue", "[Debit] > 0 OR [Credit] > 0");
                        });
                });

            modelBuilder.Entity("SBC.Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SBC.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SBC.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SBC.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SBC.Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SBC.Domain.Entities.Accounting.Account", b =>
                {
                    b.HasOne("SBC.Domain.Entities.Accounting.Account", "ParentAccount")
                        .WithMany("SubAccounts")
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("SBC.Domain.Entities.Accounting.AccountingPeriod", b =>
                {
                    b.HasOne("SBC.Domain.Entities.Accounting.JournalEntry", "ClosingJournalEntry")
                        .WithMany()
                        .HasForeignKey("ClosingJournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClosingJournalEntry");
                });

            modelBuilder.Entity("SBC.Domain.Entities.Accounting.JournalEntryLine", b =>
                {
                    b.HasOne("SBC.Domain.Entities.Accounting.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SBC.Domain.Entities.Accounting.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("SBC.Domain.Entities.Accounting.Account", b =>
                {
                    b.Navigation("SubAccounts");
                });

            modelBuilder.Entity("SBC.Domain.Entities.Accounting.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
